version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=banka4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  redis:
    image: 'redis:latest'
    container_name: rdb
    ports:
      - "6379:6379"